trigger:
- Production

pool:
  name: 'Default'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'


- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*test*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/MozaeekCore.RestAPI.csproj'
    arguments: '-o $(System.DefaultWorkingDirectory)/OutputProduction /p:Configuration=Release /p:EnvironmentName=Production '
    zipAfterPublish: false
    modifyOutputPath: true
    
