// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MozaeekCore.Persistense.EF;

namespace MozaeekCore.Persistense.EF.Migrations
{
    [DbContext(typeof(CoreDomainContext))]
    partial class CoreDomainContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MozaeekCore.Domain.Label", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Label");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Title = "label1"
                        },
                        new
                        {
                            Id = 2L,
                            ParentId = 1L,
                            Title = "LabelChild"
                        });
                });

            modelBuilder.Entity("MozaeekCore.Domain.Label", b =>
                {
                    b.HasOne("MozaeekCore.Domain.Label", "Parent")
                        .WithMany("SubLabels")
                        .HasForeignKey("ParentId");
                });
#pragma warning restore 612, 618
        }
    }
}
